#include "hwbp_core.h"
#include "hwbp_core_regs.h"
#include "hwbp_core_types.h"

#include "app.h"
#include "app_funcs.h"
#include "app_ios_and_regs.h"

extern AppRegs app_regs;

void core_callback_reset_registers(void)
{
	/* Initialize registers */
	app_regs.REG_ENABLE_MOTORS = 0;
	app_regs.REG_ENABLE_INPUTS = 0;
	app_regs.REG_ENABLE_ENCODERS = 0;
	
	
	app_regs.REG_MOTOR0_OPERATION_MODE = GM_QUIET_MODE;
	app_regs.REG_MOTOR0_MICROSTEP_RESOLUTION = GM_MICROSTEPS_8;
	app_regs.REG_MOTOR0_MAXIMUM_CURRENT_RMS = 0.2;
	app_regs.REG_MOTOR0_HOLD_CURRENT_REDUCTION = GM_REDUCTION_TO_50PCT;
	app_regs.REG_MOTOR0_NOMINAL_STEP_INTERVAL = 250;
	app_regs.REG_MOTOR0_MAXIMUM_STEP_INTERVAL = 2000;
	app_regs.REG_MOTOR0_STEP_ACCELERATION_INTERVAL = 10;
	
	app_regs.REG_MOTOR1_OPERATION_MODE = GM_QUIET_MODE;
	app_regs.REG_MOTOR1_MICROSTEP_RESOLUTION = GM_MICROSTEPS_8;
	app_regs.REG_MOTOR1_MAXIMUM_CURRENT_RMS = 0.2;
	app_regs.REG_MOTOR1_HOLD_CURRENT_REDUCTION = GM_REDUCTION_TO_50PCT;
	app_regs.REG_MOTOR1_NOMINAL_STEP_INTERVAL = 250;
	app_regs.REG_MOTOR1_MAXIMUM_STEP_INTERVAL = 2000;
	app_regs.REG_MOTOR1_STEP_ACCELERATION_INTERVAL = 10;
	
	app_regs.REG_MOTOR2_OPERATION_MODE = GM_QUIET_MODE;
	app_regs.REG_MOTOR2_MICROSTEP_RESOLUTION = GM_MICROSTEPS_8;
	app_regs.REG_MOTOR2_MAXIMUM_CURRENT_RMS = 0.2;
	app_regs.REG_MOTOR2_HOLD_CURRENT_REDUCTION = GM_REDUCTION_TO_50PCT;
	app_regs.REG_MOTOR2_NOMINAL_STEP_INTERVAL = 250;
	app_regs.REG_MOTOR2_MAXIMUM_STEP_INTERVAL = 2000;
	app_regs.REG_MOTOR2_STEP_ACCELERATION_INTERVAL = 10;
	
	app_regs.REG_MOTOR3_OPERATION_MODE = GM_QUIET_MODE;
	app_regs.REG_MOTOR3_MICROSTEP_RESOLUTION = GM_MICROSTEPS_8;
	app_regs.REG_MOTOR3_MAXIMUM_CURRENT_RMS = 0.2;
	app_regs.REG_MOTOR3_HOLD_CURRENT_REDUCTION = GM_REDUCTION_TO_50PCT;
	app_regs.REG_MOTOR3_NOMINAL_STEP_INTERVAL = 250;
	app_regs.REG_MOTOR3_MAXIMUM_STEP_INTERVAL = 2000;
	app_regs.REG_MOTOR3_STEP_ACCELERATION_INTERVAL = 10;	
	
	app_regs.REG_ENCODERS_UPDATE_RATE = GM_RATE_100HZ;
	
	app_regs.REG_INPUT0_OPERATION_MODE = GM_STOP_MOTOR0_ON_RISING;
	app_regs.REG_INPUT1_OPERATION_MODE = GM_STOP_MOTOR1_ON_RISING;
	app_regs.REG_INPUT2_OPERATION_MODE = GM_STOP_MOTOR2_ON_RISING;
	app_regs.REG_INPUT3_OPERATION_MODE = GM_STOP_MOTOR3_ON_RISING;
	
	app_regs.REG_ACCUMULATED_STEPS_UPDATE_RATE = GM_AS_DISABLED;
	
	app_regs.REG_MOTORS_ERROR_DETECTTION = 0;
		
	app_regs.REG_ACCUMULATED_STEPS[0] = 0;
	app_regs.REG_ACCUMULATED_STEPS[1] = 0;
	app_regs.REG_ACCUMULATED_STEPS[2] = 0;
	app_regs.REG_ACCUMULATED_STEPS[3] = 0;
	
	app_regs.REG_MOTOR0_MAX_STEPS_INTEGRATION = 0;
	app_regs.REG_MOTOR0_MIN_STEPS_INTEGRATION = 0;
	
	app_regs.REG_MOTOR1_MAX_STEPS_INTEGRATION = 0;
	app_regs.REG_MOTOR1_MIN_STEPS_INTEGRATION = 0;
	
	app_regs.REG_MOTOR2_MAX_STEPS_INTEGRATION = 0;
	app_regs.REG_MOTOR2_MIN_STEPS_INTEGRATION = 0;
	
	app_regs.REG_MOTOR3_MAX_STEPS_INTEGRATION = 0;
	app_regs.REG_MOTOR3_MIN_STEPS_INTEGRATION = 0;
	
	app_regs.REG_MOTOR1_QUICK_PULSE_DISTANCE = 1.25;	// 1.25 or 2.5
	app_regs.REG_MOTOR2_QUICK_PULSE_DISTANCE = 1.25;
	app_regs.REG_MOTOR1_QUICK_NOMINAL_SPEED = 120.0;	// 90 to 150
	app_regs.REG_MOTOR2_QUICK_NOMINAL_SPEED = 120.0;
	app_regs.REG_MOTOR1_QUICK_START_SPEED = 1.0;		// 1 to 10
	app_regs.REG_MOTOR2_QUICK_START_SPEED = 1.0;
	app_regs.REG_MOTOR1_QUICK_ACCELERATION = 1.0;				// 1.0 to 3.0
	app_regs.REG_MOTOR2_QUICK_ACCELERATION = 1.0;
	app_regs.REG_MOTOR1_QUICK_DISTANCE = 15.0;			// Up to travel range
	app_regs.REG_MOTOR2_QUICK_DISTANCE = 15.0;
}

void core_callback_registers_were_reinitialized(void)
{
	/* Update registers if needed */
	
	app_write_REG_ENABLE_MOTORS(&app_regs.REG_ENABLE_MOTORS);	// Motors are disabled by io default
	app_write_REG_ENABLE_INPUTS(&app_regs.REG_ENABLE_INPUTS);
	app_write_REG_ENABLE_ENCODERS(&app_regs.REG_ENABLE_ENCODERS);
	
	app_write_REG_MOTOR0_OPERATION_MODE(&app_regs.REG_MOTOR0_OPERATION_MODE);
	app_write_REG_MOTOR0_MICROSTEP_RESOLUTION(&app_regs.REG_MOTOR0_MICROSTEP_RESOLUTION);
	app_write_REG_MOTOR0_MAXIMUM_CURRENT_RMS(&app_regs.REG_MOTOR0_MAXIMUM_CURRENT_RMS);
	app_write_REG_MOTOR0_HOLD_CURRENT_REDUCTION(&app_regs.REG_MOTOR0_HOLD_CURRENT_REDUCTION);
	app_write_REG_MOTOR0_NOMINAL_STEP_INTERVAL(&app_regs.REG_MOTOR0_NOMINAL_STEP_INTERVAL);
	app_write_REG_MOTOR0_MAXIMUM_STEP_INTERVAL(&app_regs.REG_MOTOR0_MAXIMUM_STEP_INTERVAL);
	app_write_REG_MOTOR0_STEP_ACCELERATION_INTERVAL(&app_regs.REG_MOTOR0_STEP_ACCELERATION_INTERVAL);
	
	app_write_REG_MOTOR1_OPERATION_MODE(&app_regs.REG_MOTOR1_OPERATION_MODE);
	app_write_REG_MOTOR1_MICROSTEP_RESOLUTION(&app_regs.REG_MOTOR1_MICROSTEP_RESOLUTION);
	app_write_REG_MOTOR1_MAXIMUM_CURRENT_RMS(&app_regs.REG_MOTOR1_MAXIMUM_CURRENT_RMS);
	app_write_REG_MOTOR1_HOLD_CURRENT_REDUCTION(&app_regs.REG_MOTOR1_HOLD_CURRENT_REDUCTION);
	app_write_REG_MOTOR1_NOMINAL_STEP_INTERVAL(&app_regs.REG_MOTOR1_NOMINAL_STEP_INTERVAL);
	app_write_REG_MOTOR1_MAXIMUM_STEP_INTERVAL(&app_regs.REG_MOTOR1_MAXIMUM_STEP_INTERVAL);
	app_write_REG_MOTOR1_STEP_ACCELERATION_INTERVAL(&app_regs.REG_MOTOR1_STEP_ACCELERATION_INTERVAL);
	
	app_write_REG_MOTOR2_OPERATION_MODE(&app_regs.REG_MOTOR2_OPERATION_MODE);
	app_write_REG_MOTOR2_MICROSTEP_RESOLUTION(&app_regs.REG_MOTOR2_MICROSTEP_RESOLUTION);
	app_write_REG_MOTOR2_MAXIMUM_CURRENT_RMS(&app_regs.REG_MOTOR2_MAXIMUM_CURRENT_RMS);
	app_write_REG_MOTOR2_HOLD_CURRENT_REDUCTION(&app_regs.REG_MOTOR2_HOLD_CURRENT_REDUCTION);
	app_write_REG_MOTOR2_NOMINAL_STEP_INTERVAL(&app_regs.REG_MOTOR2_NOMINAL_STEP_INTERVAL);
	app_write_REG_MOTOR2_MAXIMUM_STEP_INTERVAL(&app_regs.REG_MOTOR2_MAXIMUM_STEP_INTERVAL);
	app_write_REG_MOTOR2_STEP_ACCELERATION_INTERVAL(&app_regs.REG_MOTOR2_STEP_ACCELERATION_INTERVAL);
	
	app_write_REG_MOTOR3_OPERATION_MODE(&app_regs.REG_MOTOR3_OPERATION_MODE);
	app_write_REG_MOTOR3_MICROSTEP_RESOLUTION(&app_regs.REG_MOTOR3_MICROSTEP_RESOLUTION);
	app_write_REG_MOTOR3_MAXIMUM_CURRENT_RMS(&app_regs.REG_MOTOR3_MAXIMUM_CURRENT_RMS);
	app_write_REG_MOTOR3_HOLD_CURRENT_REDUCTION(&app_regs.REG_MOTOR3_HOLD_CURRENT_REDUCTION);
	app_write_REG_MOTOR3_NOMINAL_STEP_INTERVAL(&app_regs.REG_MOTOR3_NOMINAL_STEP_INTERVAL);
	app_write_REG_MOTOR3_MAXIMUM_STEP_INTERVAL(&app_regs.REG_MOTOR3_MAXIMUM_STEP_INTERVAL);
	app_write_REG_MOTOR3_STEP_ACCELERATION_INTERVAL(&app_regs.REG_MOTOR3_STEP_ACCELERATION_INTERVAL);
	
	app_read_REG_MOTORS_ERROR_DETECTTION();
	app_read_REG_DIGITAL_INPUTS_STATE();
	
	app_write_REG_MOTOR1_QUICK_PULSE_DISTANCE(&app_regs.REG_MOTOR1_QUICK_PULSE_DISTANCE);
	app_write_REG_MOTOR2_QUICK_PULSE_DISTANCE(&app_regs.REG_MOTOR2_QUICK_PULSE_DISTANCE);
	app_write_REG_MOTOR1_QUICK_NOMINAL_SPEED(&app_regs.REG_MOTOR1_QUICK_NOMINAL_SPEED);
	app_write_REG_MOTOR2_QUICK_NOMINAL_SPEED(&app_regs.REG_MOTOR2_QUICK_NOMINAL_SPEED);
	app_write_REG_MOTOR1_QUICK_START_SPEED(&app_regs.REG_MOTOR1_QUICK_START_SPEED);
	app_write_REG_MOTOR2_QUICK_START_SPEED(&app_regs.REG_MOTOR2_QUICK_START_SPEED);
	app_write_REG_MOTOR1_QUICK_DISTANCE(&app_regs.REG_MOTOR2_QUICK_START_SPEED);
	app_write_REG_MOTOR2_QUICK_DISTANCE(&app_regs.REG_MOTOR2_QUICK_START_SPEED);
}